all:run 
SRC_FILES=Tree.cpp LOrder.cpp Size.cpp Height.cpp DeleteTree.cpp MirrorTree.cpp Max.cpp RootToLeafPath.cpp \
NumberOfLeafNodes.cpp Ancestors.cpp CheckSumTree.cpp LowestCommonAncestor.cpp hasPathSum.cpp SubTree.cpp
HEADER_FILES=Tree.h
#run:
#       g++ $(SRC_FILES) -o run
.SUFFIXES : .o .cpp .c
run:$(SRC_FILES) $(HEADER_FILES)
	g++ $(SRC_FILES) -o run
