all:run 
SRC_FILES=BST.cpp DeleteNode.cpp CheckIfBST.cpp LCA.cpp InOrderSucc.cpp Kth.cpp BST_from_PreOrder.cpp
HEADER_FILES=BST.h
#run:
#       g++ $(SRC_FILES) -o run
.SUFFIXES : .o .cpp .c
run:$(SRC_FILES) $(HEADER_FILES)
	g++ $(SRC_FILES) -o run
